import {
  stringToClassName,
  generateWidgetCode,
} from "../common/numToAutoFixed";
import { retrieveTopFill } from "../common/retrieveFill";
import { FlutterDefaultBuilder } from "./flutterDefaultBuilder";
import { FlutterTextBuilder } from "./flutterTextBuilder";
import { indentString } from "../common/indentString";

import {
  getCrossAxisAlignment,
  getMainAxisAlignment,
  getWrapAlignment,
  getWrapRunAlignment,
} from "./builderImpl/flutterAutoLayout";
import { PluginSettings } from "types";
import { addWarning } from "../common/commonConversionWarnings";
import { getVisibleNodes } from "../common/nodeVisibility";

let localSettings: PluginSettings;
let previousExecutionCache: string[];

const getFullAppTemplate = (name: string, injectCode: string): string =>
  `import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          ${name}(),
        ]),
      ),
    );
  }
}

class ${name} extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ${indentString(injectCode, 4).trimStart()};
  }
}`;

const getStatelessTemplate = (name: string, injectCode: string): string =>
  `class ${name} extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ${indentString(injectCode, 4).trimStart()};
  }
}`;

/**
 * Checks if a widget is truly empty (contains no meaningful content)
 */
const isEmptyWidget = (widget: string): boolean => {
  if (!widget || widget.trim() === "") {
    return true;
  }
  
  // Check for empty Stack, Column, Row patterns
  const emptyPatterns = [
    /Stack\(\s*\)/,
    /Stack\(\s*children:\s*\[\s*\],?\s*\)/,
    /Column\(\s*\)/,
    /Column\(\s*children:\s*\[\s*\],?\s*\)/,
    /Row\(\s*\)/,
    /Row\(\s*children:\s*\[\s*\],?\s*\)/,
  ];
  
  return emptyPatterns.some(pattern => pattern.test(widget));
};

export const flutterMain = (
  sceneNode: ReadonlyArray<SceneNode>,
  settings: PluginSettings,
): string => {
  localSettings = settings;
  previousExecutionCache = [];

  let result = flutterWidgetGenerator(sceneNode);
  switch (localSettings.flutterGenerationMode) {
    case "snippet":
      return result;
    case "stateless":
      if (!result.startsWith("Column")) {
        result = generateWidgetCode("Column", { children: [result] });
      }
      return getStatelessTemplate(stringToClassName(sceneNode[0].name), result);
    case "fullApp":
      if (!result.startsWith("Column")) {
        result = generateWidgetCode("Column", { children: [result] });
      }
      return getFullAppTemplate(stringToClassName(sceneNode[0].name), result);
  }

  return result;
};

const flutterWidgetGenerator = (
  sceneNode: ReadonlyArray<SceneNode>,
  stackParentContext?: { absoluteBoundingBox: any, name: string }
): string => {
  let comp: string[] = [];

  // filter non visible nodes. This is necessary at this step because conversion already happened.
  const visibleSceneNode = getVisibleNodes(sceneNode);

  visibleSceneNode.forEach((node) => {
    let widgetResult = "";
    
    switch (node.type) {
      case "RECTANGLE":
      case "ELLIPSE":
      case "STAR":
      case "POLYGON":
      case "LINE":
        // Only create container if it has meaningful styling
        if (hasVisualStyling(node)) {
          widgetResult = flutterContainer(node, "", stackParentContext);
        }
        break;
      case "GROUP":
        widgetResult = flutterGroup(node, stackParentContext);
        break;
      case "FRAME":
      case "INSTANCE":
      case "COMPONENT":
      case "COMPONENT_SET":
        widgetResult = flutterFrame(node, stackParentContext);
        break;
      case "SECTION":
        // Only create container if it has meaningful styling
        if (hasVisualStyling(node)) {
          widgetResult = flutterContainer(node, "", stackParentContext);
        }
        break;
      case "TEXT":
        widgetResult = flutterText(node, stackParentContext);
        break;
      case "VECTOR":
        addWarning("VectorNodes are not supported in Flutter");
        break;
      case "SLICE":
        break;
      case "BOOLEAN_OPERATION":
        addWarning("BOOLEAN_OPERATION node is not supported");
        break;
      default:
        break;
    }
    
    // Only add widget to comp if it's not empty (including empty Stack/Container patterns)
    if (widgetResult && widgetResult.trim() !== "" && !isEmptyWidget(widgetResult)) {
      comp.push(widgetResult);
    }
  });

  // Filter out empty widgets before joining (including empty Stack/Container patterns)
  const meaningfulWidgets = comp.filter(widget => widget && widget.trim() !== "" && !isEmptyWidget(widget));
  return meaningfulWidgets.join(",\n");
};

const flutterGroup = (node: GroupNode, stackParentContext?: { absoluteBoundingBox: any, name: string }): string => {
  const widget = flutterWidgetGenerator(node.children, stackParentContext);
  
  // Don't create Stack if there are no children
  if (!widget || widget.trim() === "") {
    return hasVisualStyling(node) ? flutterContainer(node, "", stackParentContext) : "";
  }
  
  const stackWidget = generateWidgetCode("Stack", {
    children: [widget],
  });
  
  // Check if the generated Stack would be empty (recursive empty propagation)
  if (isEmptyWidget(stackWidget)) {
    return hasVisualStyling(node) ? flutterContainer(node, "", stackParentContext) : "";
  }
  
  // Only wrap in Container if styling is needed
  const needsContainerStyling = hasVisualStyling(node);
  return needsContainerStyling ? flutterContainer(node, stackWidget, stackParentContext) : stackWidget;
};

const flutterContainer = (node: SceneNode, child: string, stackParentContext?: { absoluteBoundingBox: any, name: string }): string => {
  let propChild = "";

  if ("fills" in node && retrieveTopFill(node.fills as any)?.type === "IMAGE") {
    addWarning("Image fills are replaced with placeholders");
  }

  if (child.length > 0) {
    propChild = child;
  }

  const builder = new FlutterDefaultBuilder(propChild)
    .createContainer(node)
    .blendAttr(node);
    
  // Pass Stack context to positioning logic
  if (stackParentContext) {
    builder.positionInStack(node, stackParentContext);
  } else {
    builder.position(node);
  }

  return builder.child;
};

const flutterText = (node: TextNode, stackParentContext?: { absoluteBoundingBox: any, name: string }): string => {
  const builder = new FlutterTextBuilder().createText(node);
  previousExecutionCache.push(builder.child);

  const textBuilder = builder.blendAttr(node).textAutoSize(node);
  
  // Pass Stack context to positioning logic
  if (stackParentContext) {
    textBuilder.positionInStack(node, stackParentContext);
  } else {
    textBuilder.position(node);
  }
  
  return textBuilder.child;
};

const flutterFrame = (
  node: SceneNode & BaseFrameMixin & MinimalBlendMixin,
  stackParentContext?: { absoluteBoundingBox: any, name: string }
): string => {
  // Debug layout properties
  console.log(`[LAYOUT DEBUG] Frame "${node.name}":`, {
    layoutMode: (node as any).layoutMode,
    inferredAutoLayout: (node as any).inferredAutoLayout,
    primaryAxisSizingMode: (node as any).primaryAxisSizingMode,
    counterAxisSizingMode: (node as any).counterAxisSizingMode,
    itemSpacing: (node as any).itemSpacing,
    paddingLeft: (node as any).paddingLeft,
    paddingRight: (node as any).paddingRight,
    paddingTop: (node as any).paddingTop,
    paddingBottom: (node as any).paddingBottom
  });

  // Check if any direct children need absolute positioning
  const hasAbsoluteChildren = node.children.some(
    (child: any) => (child as any).layoutPositioning === "ABSOLUTE",
  );

  // Check if this is a root frame with explicit dimensions
  const isRootFrame = !(node as any).parent;

  // Add warning if we need to use Stack due to absolute positioning
  if (hasAbsoluteChildren && node.layoutMode !== "NONE") {
    addWarning(
      `Frame "${node.name}" has absolute positioned children. Using Stack instead of ${
        node.layoutMode === "HORIZONTAL" ? "Row" : "Column"
      }.`,
    );
  }

  // Generate widget code for children
  // Only pass Stack context when this frame will actually generate a Stack widget
  let childContext = stackParentContext;
  
  // Determine if THIS frame will generate a Stack (not just inherit context)
  const thisFrameGeneratesStack = (hasAbsoluteChildren || isRootFrame || node.layoutMode === "NONE") ||
    (!node.layoutMode && !node.inferredAutoLayout);
  
  if (thisFrameGeneratesStack) {
    childContext = { 
      absoluteBoundingBox: (node as any).absoluteBoundingBox,
      name: node.name 
    };
  }
  
  const children = flutterWidgetGenerator(node.children, childContext);


  // PRIORITY 1: Auto-layout detected - use Column/Row (even if has absolute children or is root)
  if (node.layoutMode && (node.layoutMode as any) !== "NONE") {
    console.log(`[LAYOUT DEBUG] Using auto-layout for ${node.name}: ${node.layoutMode}`);
    // For Row/Column layouts, generate children WITHOUT Stack context (no positioning)
    const rowColumnChildren = flutterWidgetGenerator(node.children);
    const rowColumnWrap = makeRowColumnWrap(node, rowColumnChildren);
    console.log(`[LAYOUT DEBUG] Generated ${node.layoutMode === 'HORIZONTAL' ? 'Row' : 'Column'} for ${node.name}`);
    // Check if this frame needs Container wrapper for styling
    const needsContainerStyling = hasVisualStyling(node);
    return needsContainerStyling ? flutterContainer(node, rowColumnWrap, stackParentContext) : rowColumnWrap;
  } else if (node.inferredAutoLayout) {
    console.log(`[LAYOUT DEBUG] Using inferred auto-layout for ${node.name}`);
    // For Row/Column layouts, generate children WITHOUT Stack context (no positioning)
    const rowColumnChildren = flutterWidgetGenerator(node.children);
    const rowColumnWrap = makeRowColumnWrap(node.inferredAutoLayout, rowColumnChildren);
    // Check if this frame needs Container wrapper for styling
    const needsContainerStyling = hasVisualStyling(node);
    return needsContainerStyling ? flutterContainer(node, rowColumnWrap, stackParentContext) : rowColumnWrap;
  }

  // PRIORITY 2: Fall back to Stack only when no auto-layout is available
  console.log(`[LAYOUT DEBUG] Using Stack for ${node.name} because no auto-layout detected:`, {
    hasAbsoluteChildren,
    isRootFrame, 
    noLayoutMode: !node.layoutMode,
    layoutModeNone: (node.layoutMode as any) === "NONE"
  });
  
  // Don't create Stack if there are no meaningful children
  if (children === "" || children.trim() === "") {
    // Return empty widget or minimal container only if styling is needed
    return hasVisualStyling(node) ? flutterContainer(node, "", stackParentContext) : "";
  }
  
  const stackWidget = generateWidgetCode("Stack", {
    children: [children],
  });
  
  // Check if the generated Stack would be empty (recursive empty propagation)
  if (isEmptyWidget(stackWidget)) {
    return hasVisualStyling(node) ? flutterContainer(node, "", stackParentContext) : "";
  }
  
  // Only wrap in Container if styling is needed
  const needsContainerStyling = hasVisualStyling(node);
  return needsContainerStyling ? flutterContainer(node, stackWidget, stackParentContext) : stackWidget;
};

const makeRowColumnWrap = (
  autoLayout: InferredAutoLayoutResult,
  children: string,
): string => {
  const rowOrColumn = autoLayout.layoutWrap == "WRAP" && autoLayout.primaryAxisSizingMode == "FIXED" ?
    "Wrap" : autoLayout.layoutMode === "HORIZONTAL" ? "Row" : "Column";

  const widgetProps: Record<string, any> = autoLayout.layoutWrap == "WRAP"
    ? {
      alignment: getWrapAlignment(autoLayout),
      runAlignment: getWrapRunAlignment(autoLayout),
    } : 
    {
      mainAxisSize: "MainAxisSize.min",
      // mainAxisSize: getFlex(node, autoLayout),
      mainAxisAlignment: getMainAxisAlignment(autoLayout),
      crossAxisAlignment: getCrossAxisAlignment(autoLayout),
      
    };

  // Add spacing parameter if itemSpacing is set
  if (autoLayout.layoutWrap == "WRAP") {
    if (autoLayout.primaryAxisAlignItems != "SPACE_BETWEEN" && autoLayout.itemSpacing != undefined) {
      widgetProps.spacing = autoLayout.itemSpacing;
    }
    if (autoLayout.counterAxisAlignContent != "SPACE_BETWEEN" && autoLayout.counterAxisSpacing != undefined) {
      widgetProps.runSpacing = autoLayout.counterAxisSpacing;
    }
  } else if (autoLayout.itemSpacing > 0) {
    widgetProps.spacing = autoLayout.itemSpacing;
  } else if (autoLayout.itemSpacing < 0) {
    addWarning("Flutter doesn't support negative itemSpacing");
  }

  widgetProps.children = [children];

  return generateWidgetCode(rowOrColumn, widgetProps);
};

const hasVisualStyling = (node: SceneNode): boolean => {
  // More selective check - only create Container when visual styling is actually needed
  
  // Check for meaningful background fills (not transparent/invisible)
  if ("fills" in node && node.fills && Array.isArray(node.fills) && node.fills.length > 0) {
    const topFill = retrieveTopFill(node.fills as any);
    if (topFill && topFill.visible !== false) {
      // Skip transparent or very low opacity fills
      if (topFill.type === "SOLID" && topFill.color && topFill.color.a < 0.01) {
        // Skip nearly transparent fills
      } else {
        return true;
      }
    }
  }
  
  // Has meaningful border/stroke (not minimal)
  if ("strokeWeight" in node && node.strokeWeight && Number(node.strokeWeight) > 0.5) {
    return true;
  }
  
  // Has significant padding (not minimal)
  if ("paddingLeft" in node) {
    const totalPadding = (Number(node.paddingLeft) || 0) + (Number(node.paddingRight) || 0) + (Number(node.paddingTop) || 0) + (Number(node.paddingBottom) || 0);
    if (totalPadding > 2) { // Only meaningful padding
      return true;
    }
  }
  
  // Has meaningful corner radius
  if ("cornerRadius" in node && node.cornerRadius && Number(node.cornerRadius) > 2) {
    return true;
  }
  
  // Has important clipping
  if ("clipsContent" in node && node.clipsContent === true) {
    return true;
  }
  
  // Has rotation
  if ("rotation" in node && node.rotation && Math.abs(node.rotation) > 0.01) {
    return true;
  }
  
  // Has visible shadow effects
  if ("effects" in node && node.effects && Array.isArray(node.effects) && node.effects.length > 0) {
    const hasVisibleEffects = node.effects.some(effect => 
      effect.visible !== false && 
      (effect.type === "DROP_SHADOW" || effect.type === "INNER_SHADOW" || effect.type === "LAYER_BLUR")
    );
    if (hasVisibleEffects) {
      return true;
    }
  }
  
  
  return false;
};

export const flutterCodeGenTextStyles = () => {
  const result = previousExecutionCache
    .map((style) => `${style}`)
    .join("\n// ---\n");

  if (!result) {
    return "// No text styles in this selection";
  }
  return result;
};
