import {
  stringToClassName,
  generateWidgetCode,
} from "../common/numToAutoFixed";
import { retrieveTopFill } from "../common/retrieveFill";
import { FlutterDefaultBuilder } from "./flutterDefaultBuilder";
import { FlutterTextBuilder } from "./flutterTextBuilder";
import { indentString } from "../common/indentString";

import {
  getCrossAxisAlignment,
  getMainAxisAlignment,
  getWrapAlignment,
  getWrapRunAlignment,
} from "./builderImpl/flutterAutoLayout";
import { PluginSettings } from "types";
import { addWarning } from "../common/commonConversionWarnings";
import { getVisibleNodes } from "../common/nodeVisibility";
import { retrieveTopFill } from "../common/retrieveFill";

let localSettings: PluginSettings;
let previousExecutionCache: string[];

const getFullAppTemplate = (name: string, injectCode: string): string =>
  `import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          ${name}(),
        ]),
      ),
    );
  }
}

class ${name} extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ${indentString(injectCode, 4).trimStart()};
  }
}`;

const getStatelessTemplate = (name: string, injectCode: string): string =>
  `class ${name} extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ${indentString(injectCode, 4).trimStart()};
  }
}`;

export const flutterMain = (
  sceneNode: ReadonlyArray<SceneNode>,
  settings: PluginSettings,
): string => {
  localSettings = settings;
  previousExecutionCache = [];

  let result = flutterWidgetGenerator(sceneNode);
  switch (localSettings.flutterGenerationMode) {
    case "snippet":
      return result;
    case "stateless":
      if (!result.startsWith("Column")) {
        result = generateWidgetCode("Column", { children: [result] });
      }
      return getStatelessTemplate(stringToClassName(sceneNode[0].name), result);
    case "fullApp":
      if (!result.startsWith("Column")) {
        result = generateWidgetCode("Column", { children: [result] });
      }
      return getFullAppTemplate(stringToClassName(sceneNode[0].name), result);
  }

  return result;
};

const flutterWidgetGenerator = (
  sceneNode: ReadonlyArray<SceneNode>,
  stackParentContext?: { absoluteBoundingBox: any, name: string }
): string => {
  let comp: string[] = [];

  // filter non visible nodes. This is necessary at this step because conversion already happened.
  const visibleSceneNode = getVisibleNodes(sceneNode);

  visibleSceneNode.forEach((node) => {
    switch (node.type) {
      case "RECTANGLE":
      case "ELLIPSE":
      case "STAR":
      case "POLYGON":
      case "LINE":
        comp.push(flutterContainer(node, "", stackParentContext));
        break;
      case "GROUP":
        comp.push(flutterGroup(node, stackParentContext));
        break;
      case "FRAME":
      case "INSTANCE":
      case "COMPONENT":
      case "COMPONENT_SET":
        comp.push(flutterFrame(node, stackParentContext));
        break;
      case "SECTION":
        comp.push(flutterContainer(node, "", stackParentContext));
        break;
      case "TEXT":
        comp.push(flutterText(node, stackParentContext));
        break;
      case "VECTOR":
        addWarning("VectorNodes are not supported in Flutter");
        break;
      case "SLICE":
      default:
      // do nothing
    }
  });

  return comp.join(",\n");
};

const flutterGroup = (node: GroupNode, stackParentContext?: { absoluteBoundingBox: any, name: string }): string => {
  const widget = flutterWidgetGenerator(node.children, stackParentContext);
  return flutterContainer(
    node,
    generateWidgetCode("Stack", {
      children: widget ? [widget] : [],
    }),
    stackParentContext
  );
};

const flutterContainer = (node: SceneNode, child: string, stackParentContext?: { absoluteBoundingBox: any, name: string }): string => {
  let propChild = "";

  if ("fills" in node && retrieveTopFill(node.fills as any)?.type === "IMAGE") {
    addWarning("Image fills are replaced with placeholders");
  }

  if (child.length > 0) {
    propChild = child;
  }

  const builder = new FlutterDefaultBuilder(propChild)
    .createContainer(node)
    .blendAttr(node);
    
  // Pass Stack context to positioning logic
  if (stackParentContext) {
    builder.positionInStack(node, stackParentContext);
  } else {
    builder.position(node);
  }

  return builder.child;
};

const flutterText = (node: TextNode, stackParentContext?: { absoluteBoundingBox: any, name: string }): string => {
  const builder = new FlutterTextBuilder().createText(node);
  previousExecutionCache.push(builder.child);

  const textBuilder = builder.blendAttr(node).textAutoSize(node);
  
  // Pass Stack context to positioning logic
  if (stackParentContext) {
    textBuilder.positionInStack(node, stackParentContext);
  } else {
    textBuilder.position(node);
  }
  
  return textBuilder.child;
};

const flutterFrame = (
  node: SceneNode & BaseFrameMixin & MinimalBlendMixin,
  stackParentContext?: { absoluteBoundingBox: any, name: string }
): string => {
  // Check if any direct children need absolute positioning
  const hasAbsoluteChildren = node.children.some(
    (child: any) => (child as any).layoutPositioning === "ABSOLUTE",
  );

  // Check if this is a root frame with explicit dimensions
  const isRootFrame = !(node as any).parent;

  // Add warning if we need to use Stack due to absolute positioning
  if (hasAbsoluteChildren && node.layoutMode !== "NONE") {
    addWarning(
      `Frame "${node.name}" has absolute positioned children. Using Stack instead of ${
        node.layoutMode === "HORIZONTAL" ? "Row" : "Column"
      }.`,
    );
  }

  // Generate widget code for children
  // Only pass Stack context when this frame will actually generate a Stack widget
  let childContext = stackParentContext;
  
  // Determine if THIS frame will generate a Stack (not just inherit context)
  const thisFrameGeneratesStack = (hasAbsoluteChildren || isRootFrame || node.layoutMode === "NONE") ||
    (!node.layoutMode && !node.inferredAutoLayout);
  
  if (thisFrameGeneratesStack) {
    childContext = { 
      absoluteBoundingBox: (node as any).absoluteBoundingBox,
      name: node.name 
    };
    console.log(`Frame "${node.name}" will generate Stack - passing context to children`);
  }
  
  const children = flutterWidgetGenerator(node.children, childContext);

  // Debug only specific frames that should use Stack
  if (node.name.includes("Frame 1412769182") || node.name.includes("header") || (node.children && node.children.some((child: any) => child.name === "Label"))) {
    console.log(`LAYOUT MODE DEBUG for "${node.name}":`, {
      layoutMode: node.layoutMode,
      inferredAutoLayout: !!node.inferredAutoLayout,
      hasAbsoluteChildren,
      isRootFrame,
      childNames: node.children?.map((child: any) => child.name)
    });
  }

  // Check if layoutMode is AUTO - prefer Stack for absolute positioning
  if (node.layoutMode === "AUTO") {
    console.log(`Using Stack for AUTO layoutMode: "${node.name}"`);
    return flutterContainer(
      node,
      generateWidgetCode("Stack", {
        children: children !== "" ? [children] : [],
      }),
    );
  }

  // Prioritize Column/Row layouts when auto-layout is detected
  if (node.layoutMode && (node.layoutMode as any) !== "NONE") {
    // For Row/Column layouts, generate children WITHOUT Stack context (no positioning)
    const rowColumnChildren = flutterWidgetGenerator(node.children);
    const rowColumnWrap = makeRowColumnWrap(node, rowColumnChildren);
    // Check if this frame needs Container wrapper for styling
    const needsContainerStyling = hasVisualStyling(node);
    return needsContainerStyling ? flutterContainer(node, rowColumnWrap, stackParentContext) : rowColumnWrap;
  } else if (node.inferredAutoLayout) {
    // For Row/Column layouts, generate children WITHOUT Stack context (no positioning)
    const rowColumnChildren = flutterWidgetGenerator(node.children);
    const rowColumnWrap = makeRowColumnWrap(node.inferredAutoLayout, rowColumnChildren);
    // Check if this frame needs Container wrapper for styling
    const needsContainerStyling = hasVisualStyling(node);
    return needsContainerStyling ? flutterContainer(node, rowColumnWrap, stackParentContext) : rowColumnWrap;
  }

  // Use Stack only when necessary (absolute positioned children, root frames, or no layout)
  if (hasAbsoluteChildren || isRootFrame || node.layoutMode === "NONE") {
    return flutterContainer(
      node,
      generateWidgetCode("Stack", {
        children: children !== "" ? [children] : [],
      }),
      stackParentContext
    );
  }

  if (node.isAsset) {
    return flutterContainer(node, generateWidgetCode("FlutterLogo", {}), stackParentContext);
  }

  // Default to Stack for frames without any layout info
  return flutterContainer(
    node,
    generateWidgetCode("Stack", {
      children: children !== "" ? [children] : [],
    }),
    stackParentContext
  );
};

const makeRowColumnWrap = (
  autoLayout: InferredAutoLayoutResult,
  children: string,
): string => {
  const rowOrColumn = autoLayout.layoutWrap == "WRAP" && autoLayout.primaryAxisSizingMode == "FIXED" ?
    "Wrap" : autoLayout.layoutMode === "HORIZONTAL" ? "Row" : "Column";

  const widgetProps: Record<string, any> = autoLayout.layoutWrap == "WRAP"
    ? {
      alignment: getWrapAlignment(autoLayout),
      runAlignment: getWrapRunAlignment(autoLayout),
    } : 
    {
      mainAxisSize: "MainAxisSize.min",
      // mainAxisSize: getFlex(node, autoLayout),
      mainAxisAlignment: getMainAxisAlignment(autoLayout),
      crossAxisAlignment: getCrossAxisAlignment(autoLayout),
      
    };

  // Add spacing parameter if itemSpacing is set
  if (autoLayout.layoutWrap == "WRAP") {
    if (autoLayout.primaryAxisAlignItems != "SPACE_BETWEEN" && autoLayout.itemSpacing != undefined) {
      widgetProps.spacing = autoLayout.itemSpacing;
    }
    if (autoLayout.counterAxisAlignContent != "SPACE_BETWEEN" && autoLayout.counterAxisSpacing != undefined) {
      widgetProps.runSpacing = autoLayout.counterAxisSpacing;
    }
  } else if (autoLayout.itemSpacing > 0) {
    widgetProps.spacing = autoLayout.itemSpacing;
  } else if (autoLayout.itemSpacing < 0) {
    addWarning("Flutter doesn't support negative itemSpacing");
  }

  widgetProps.children = [children];

  return generateWidgetCode(rowOrColumn, widgetProps);
};

const hasVisualStyling = (node: SceneNode): boolean => {
  // Check if node has visual properties that require Container wrapper
  
  // Has background fills or decorations
  if ("fills" in node && node.fills && Array.isArray(node.fills) && node.fills.length > 0) {
    const topFill = retrieveTopFill(node.fills as any);
    if (topFill && topFill.visible !== false) {
      return true;
    }
  }
  
  // Has border/stroke
  if ("strokeWeight" in node && node.strokeWeight && node.strokeWeight > 0) {
    return true;
  }
  
  // Has padding
  if ("paddingLeft" in node && (node.paddingLeft || node.paddingRight || node.paddingTop || node.paddingBottom)) {
    return true;
  }
  
  // Has corner radius
  if ("cornerRadius" in node && node.cornerRadius && node.cornerRadius > 0) {
    return true;
  }
  
  // Has clipping
  if ("clipsContent" in node && node.clipsContent === true) {
    return true;
  }
  
  // Has rotation
  if ("rotation" in node && node.rotation && Math.abs(node.rotation) > 0.01) {
    return true;
  }
  
  // Has shadow effects
  if ("effects" in node && node.effects && Array.isArray(node.effects) && node.effects.length > 0) {
    const hasVisibleEffects = node.effects.some(effect => effect.visible !== false);
    if (hasVisibleEffects) {
      return true;
    }
  }
  
  return false;
};

export const flutterCodeGenTextStyles = () => {
  const result = previousExecutionCache
    .map((style) => `${style}`)
    .join("\n// ---\n");

  if (!result) {
    return "// No text styles in this selection";
  }
  return result;
};
